name: HubEssentials
version: '${project.version}'
main: net.cubehunt.hubessentials.HubEssentials
api-version: 1.19
authors: [ LuuckA, matthewbolds ]
description: Hub Essentials Plugin
libraries:
  - org.spongepowered:configurate-yaml:${libs.configurate-yaml}
  - net.kyori:adventure-text-minimessage:${libs.text-minimessage}
  - net.kyori:adventure-platform-bukkit:${libs.platform-bukkit}
#permissions:
#  hubessentials.setspawn:
#    default: false
#    description: Allow user to set the spawn point
#  hubessentials.spawn:
#    default: false
#    description: Allows user to go to spawn