name: HubEssentials
version: '${project.version}'
main: net.cubehunt.hubessentials.HubEssentials
api-version: 1.19
authors: [ LuuckA, matthewbolds ]
description: Hub Essentials Plugin
softdepend: [Vault, LuckPerms]
libraries:
  - org.spongepowered:configurate-yaml:${libs.configurate-yaml}
  - net.kyori:adventure-text-minimessage:${libs.text-minimessage}
  - net.kyori:adventure-platform-bukkit:${libs.platform-bukkit}