name: HubEssentials
version: '${project.version}'
main: net.cubehunt.hubessentials.HubEssentials
api-version: 1.19
authors: [ LuuckA, matthewbolds ]
description: Hub Essentials Plugin
libraries:
  - org.spongepowered:configurate-yaml:${libs.configurate-yaml}